export const jobDetails = [
  {
    job_id: "CMfE_olpn88ocYgHAAAAAA==",
    job_posted_at_datetime_utc: "2023-12-27T14:04:59.000Z",
    job_offer_expiration_datetime_utc: "2024-01-26T14:04:59.000Z",
    job_publisher: "LinkedIn",
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=frontend+developer+in+hyderabad,india&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=frontend+developer+in+hyderabad,india&htidocid=CMfE_olpn88ocYgHAAAAAA%3D%3D",
    job_apply_link:
      "https://in.linkedin.com/jobs/view/frontend-developer-at-circuitry-ai-3788269448",
    job_is_remote: true,
    job_city: "Hyderabad",
    job_state: "TS",
    job_country: "IN",
    job_title: "Frontend Developer",
    job_employment_type: "FULLTIME",
    job_description:
      "Job Title: Front-End Developer (React)\n\nLocation: Hyderabad, India\n\nJob Type: Full-time\n\nPosition Overview: As a Front-End Developer at Circuitry.ai, you will play a crucial role in designing, developing, and maintaining user interfaces for our web and mobile applications. You will work closely with our design and back-end development teams to create visually stunning and highly functional interfaces that engage users and drive our products' success. The ideal candidate should be proficient in both React and React Native, have a strong understanding of front-end technologies, and be passionate about delivering exceptional user experiences across various platforms.\n\nKey Responsibilities:\n• Collaborate with cross-functional teams, including designers and back-end developers, to translate design mockups and user stories into responsive, interactive web and mobile applications.\n• Develop user-facing features using React.js and implement responsive web designs.\n• Build efficient and reusable components and front-end libraries\n• In-depth knowledge of JavaScript, CSS, HTML, Typescript, and front-end languages , Experience using ES2015 (ES6 / ES7)\n• Knowledge of REACT tools including React.js, Webpack, Enzyme, Redux, and Flux.\n• Experience with data structure libraries (e.g., Immutable.js)\n• Knowledge of modern authorization mechanisms, such as JWT mechanism and working with Okta.\n• Good understanding of asynchronous request handling, partial page updates for single-page applications.\n• Ability to work in an Agile /SCRUM environment.\n• Participate in code reviews and collaborate on architectural decisions.\n• Maintain and enhance existing codebases and peer-review code changes.\n\nQualifications:\n• Bachelor's degree in Computer Science, Web Development, or a related field (or equivalent experience).\n• 3 or more years of frontend experience with a product-based organization is recommended.\n• Proven experience as a Front-End Developer with a strong focus on React, React Native, and Node.JS\n• Proven experience in front-end development, specifically within Enterprise SaaS companies, demonstrating an understanding of the unique challenges and requirements of developing user interfaces for enterprise-level software.\n• Proficiency in JavaScript, HTML5, and CSS3.\n• Experience with state management libraries (e.g., Redux, MobX).\n• Knowledge of modern front-end build tools and package managers (e.g., Webpack, Babel, npm, yarn).\n• Familiarity with RESTful APIs and asynchronous request handling.\n• Responsive web design and mobile-first development experience.\n• Solid understanding of web and mobile performance optimization techniques.\n• Strong problem-solving skills and attention to detail.\n• Excellent communication and teamwork skills.\n• Ability to work independently and meet project deadlines.\n• Experience with version control systems (e.g., Github), deployment automation is a plus.",
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
    },
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 36,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_salary_currency: null,
    job_salary_period: null,
    job_min_salary: null,
    job_max_salary: null,
    job_latitude: 17.406498,
    job_longitude: 78.47724,
    job_highlights: {},
    job_apply_quality_score: 0.6875,
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
    job_benefits: null,
    employer_name: "Circuitry.ai",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqg7hLEftyxTJTlsebBjsfXNeYURotZDm9Ie08&s=0",
    employer_website: null,
    employer_company_type: null,
  },
  {
    job_id: "CMfE_olpn88ocYgHAAAAAA==",
    job_posted_at_datetime_utc: "2023-12-27T14:04:59.000Z",
    job_offer_expiration_datetime_utc: "2024-01-26T14:04:59.000Z",
    job_publisher: "LinkedIn",
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=frontend+developer+in+hyderabad,india&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=frontend+developer+in+hyderabad,india&htidocid=CMfE_olpn88ocYgHAAAAAA%3D%3D",
    job_apply_link:
      "https://in.linkedin.com/jobs/view/frontend-developer-at-circuitry-ai-3788269448",
    job_is_remote: true,
    job_city: "Hyderabad",
    job_state: "TS",
    job_country: "IN",
    job_title: "Frontend Developer",
    job_employment_type: "FULLTIME",
    job_description:
      "Job Title: Front-End Developer (React)\n\nLocation: Hyderabad, India\n\nJob Type: Full-time\n\nPosition Overview: As a Front-End Developer at Circuitry.ai, you will play a crucial role in designing, developing, and maintaining user interfaces for our web and mobile applications. You will work closely with our design and back-end development teams to create visually stunning and highly functional interfaces that engage users and drive our products' success. The ideal candidate should be proficient in both React and React Native, have a strong understanding of front-end technologies, and be passionate about delivering exceptional user experiences across various platforms.\n\nKey Responsibilities:\n• Collaborate with cross-functional teams, including designers and back-end developers, to translate design mockups and user stories into responsive, interactive web and mobile applications.\n• Develop user-facing features using React.js and implement responsive web designs.\n• Build efficient and reusable components and front-end libraries\n• In-depth knowledge of JavaScript, CSS, HTML, Typescript, and front-end languages , Experience using ES2015 (ES6 / ES7)\n• Knowledge of REACT tools including React.js, Webpack, Enzyme, Redux, and Flux.\n• Experience with data structure libraries (e.g., Immutable.js)\n• Knowledge of modern authorization mechanisms, such as JWT mechanism and working with Okta.\n• Good understanding of asynchronous request handling, partial page updates for single-page applications.\n• Ability to work in an Agile /SCRUM environment.\n• Participate in code reviews and collaborate on architectural decisions.\n• Maintain and enhance existing codebases and peer-review code changes.\n\nQualifications:\n• Bachelor's degree in Computer Science, Web Development, or a related field (or equivalent experience).\n• 3 or more years of frontend experience with a product-based organization is recommended.\n• Proven experience as a Front-End Developer with a strong focus on React, React Native, and Node.JS\n• Proven experience in front-end development, specifically within Enterprise SaaS companies, demonstrating an understanding of the unique challenges and requirements of developing user interfaces for enterprise-level software.\n• Proficiency in JavaScript, HTML5, and CSS3.\n• Experience with state management libraries (e.g., Redux, MobX).\n• Knowledge of modern front-end build tools and package managers (e.g., Webpack, Babel, npm, yarn).\n• Familiarity with RESTful APIs and asynchronous request handling.\n• Responsive web design and mobile-first development experience.\n• Solid understanding of web and mobile performance optimization techniques.\n• Strong problem-solving skills and attention to detail.\n• Excellent communication and teamwork skills.\n• Ability to work independently and meet project deadlines.\n• Experience with version control systems (e.g., Github), deployment automation is a plus.",
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
    },
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 36,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_salary_currency: null,
    job_salary_period: null,
    job_min_salary: null,
    job_max_salary: null,
    job_latitude: 17.406498,
    job_longitude: 78.47724,
    job_highlights: {},
    job_apply_quality_score: 0.6875,
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
    job_benefits: null,
    employer_name: "Circuitry.ai",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqg7hLEftyxTJTlsebBjsfXNeYURotZDm9Ie08&s=0",
    employer_website: null,
    employer_company_type: null,
  },
  {
    job_id: "CMfE_olpn88ocYgHAAAAAA==",
    job_posted_at_datetime_utc: "2023-12-27T14:04:59.000Z",
    job_offer_expiration_datetime_utc: "2024-01-26T14:04:59.000Z",
    job_publisher: "LinkedIn",
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=frontend+developer+in+hyderabad,india&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=frontend+developer+in+hyderabad,india&htidocid=CMfE_olpn88ocYgHAAAAAA%3D%3D",
    job_apply_link:
      "https://in.linkedin.com/jobs/view/frontend-developer-at-circuitry-ai-3788269448",
    job_is_remote: true,
    job_city: "Hyderabad",
    job_state: "TS",
    job_country: "IN",
    job_title: "Frontend Developer",
    job_employment_type: "FULLTIME",
    job_description:
      "Job Title: Front-End Developer (React)\n\nLocation: Hyderabad, India\n\nJob Type: Full-time\n\nPosition Overview: As a Front-End Developer at Circuitry.ai, you will play a crucial role in designing, developing, and maintaining user interfaces for our web and mobile applications. You will work closely with our design and back-end development teams to create visually stunning and highly functional interfaces that engage users and drive our products' success. The ideal candidate should be proficient in both React and React Native, have a strong understanding of front-end technologies, and be passionate about delivering exceptional user experiences across various platforms.\n\nKey Responsibilities:\n• Collaborate with cross-functional teams, including designers and back-end developers, to translate design mockups and user stories into responsive, interactive web and mobile applications.\n• Develop user-facing features using React.js and implement responsive web designs.\n• Build efficient and reusable components and front-end libraries\n• In-depth knowledge of JavaScript, CSS, HTML, Typescript, and front-end languages , Experience using ES2015 (ES6 / ES7)\n• Knowledge of REACT tools including React.js, Webpack, Enzyme, Redux, and Flux.\n• Experience with data structure libraries (e.g., Immutable.js)\n• Knowledge of modern authorization mechanisms, such as JWT mechanism and working with Okta.\n• Good understanding of asynchronous request handling, partial page updates for single-page applications.\n• Ability to work in an Agile /SCRUM environment.\n• Participate in code reviews and collaborate on architectural decisions.\n• Maintain and enhance existing codebases and peer-review code changes.\n\nQualifications:\n• Bachelor's degree in Computer Science, Web Development, or a related field (or equivalent experience).\n• 3 or more years of frontend experience with a product-based organization is recommended.\n• Proven experience as a Front-End Developer with a strong focus on React, React Native, and Node.JS\n• Proven experience in front-end development, specifically within Enterprise SaaS companies, demonstrating an understanding of the unique challenges and requirements of developing user interfaces for enterprise-level software.\n• Proficiency in JavaScript, HTML5, and CSS3.\n• Experience with state management libraries (e.g., Redux, MobX).\n• Knowledge of modern front-end build tools and package managers (e.g., Webpack, Babel, npm, yarn).\n• Familiarity with RESTful APIs and asynchronous request handling.\n• Responsive web design and mobile-first development experience.\n• Solid understanding of web and mobile performance optimization techniques.\n• Strong problem-solving skills and attention to detail.\n• Excellent communication and teamwork skills.\n• Ability to work independently and meet project deadlines.\n• Experience with version control systems (e.g., Github), deployment automation is a plus.",
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
    },
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 36,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_salary_currency: null,
    job_salary_period: null,
    job_min_salary: null,
    job_max_salary: null,
    job_latitude: 17.406498,
    job_longitude: 78.47724,
    job_highlights: {},
    job_apply_quality_score: 0.6875,
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
    job_benefits: null,
    employer_name: "Circuitry.ai",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqg7hLEftyxTJTlsebBjsfXNeYURotZDm9Ie08&s=0",
    employer_website: null,
    employer_company_type: null,
  },
  {
    job_id: "CMfE_olpn88ocYgHAAAAAA==",
    job_posted_at_datetime_utc: "2023-12-27T14:04:59.000Z",
    job_offer_expiration_datetime_utc: "2024-01-26T14:04:59.000Z",
    job_publisher: "LinkedIn",
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=frontend+developer+in+hyderabad,india&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=frontend+developer+in+hyderabad,india&htidocid=CMfE_olpn88ocYgHAAAAAA%3D%3D",
    job_apply_link:
      "https://in.linkedin.com/jobs/view/frontend-developer-at-circuitry-ai-3788269448",
    job_is_remote: true,
    job_city: "Hyderabad",
    job_state: "TS",
    job_country: "IN",
    job_title: "Frontend Developer",
    job_employment_type: "FULLTIME",
    job_description:
      "Job Title: Front-End Developer (React)\n\nLocation: Hyderabad, India\n\nJob Type: Full-time\n\nPosition Overview: As a Front-End Developer at Circuitry.ai, you will play a crucial role in designing, developing, and maintaining user interfaces for our web and mobile applications. You will work closely with our design and back-end development teams to create visually stunning and highly functional interfaces that engage users and drive our products' success. The ideal candidate should be proficient in both React and React Native, have a strong understanding of front-end technologies, and be passionate about delivering exceptional user experiences across various platforms.\n\nKey Responsibilities:\n• Collaborate with cross-functional teams, including designers and back-end developers, to translate design mockups and user stories into responsive, interactive web and mobile applications.\n• Develop user-facing features using React.js and implement responsive web designs.\n• Build efficient and reusable components and front-end libraries\n• In-depth knowledge of JavaScript, CSS, HTML, Typescript, and front-end languages , Experience using ES2015 (ES6 / ES7)\n• Knowledge of REACT tools including React.js, Webpack, Enzyme, Redux, and Flux.\n• Experience with data structure libraries (e.g., Immutable.js)\n• Knowledge of modern authorization mechanisms, such as JWT mechanism and working with Okta.\n• Good understanding of asynchronous request handling, partial page updates for single-page applications.\n• Ability to work in an Agile /SCRUM environment.\n• Participate in code reviews and collaborate on architectural decisions.\n• Maintain and enhance existing codebases and peer-review code changes.\n\nQualifications:\n• Bachelor's degree in Computer Science, Web Development, or a related field (or equivalent experience).\n• 3 or more years of frontend experience with a product-based organization is recommended.\n• Proven experience as a Front-End Developer with a strong focus on React, React Native, and Node.JS\n• Proven experience in front-end development, specifically within Enterprise SaaS companies, demonstrating an understanding of the unique challenges and requirements of developing user interfaces for enterprise-level software.\n• Proficiency in JavaScript, HTML5, and CSS3.\n• Experience with state management libraries (e.g., Redux, MobX).\n• Knowledge of modern front-end build tools and package managers (e.g., Webpack, Babel, npm, yarn).\n• Familiarity with RESTful APIs and asynchronous request handling.\n• Responsive web design and mobile-first development experience.\n• Solid understanding of web and mobile performance optimization techniques.\n• Strong problem-solving skills and attention to detail.\n• Excellent communication and teamwork skills.\n• Ability to work independently and meet project deadlines.\n• Experience with version control systems (e.g., Github), deployment automation is a plus.",
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
    },
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 36,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_salary_currency: null,
    job_salary_period: null,
    job_min_salary: null,
    job_max_salary: null,
    job_latitude: 17.406498,
    job_longitude: 78.47724,
    job_highlights: {},
    job_apply_quality_score: 0.6875,
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
    job_benefits: null,
    employer_name: "Circuitry.ai",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqg7hLEftyxTJTlsebBjsfXNeYURotZDm9Ie08&s=0",
    employer_website: null,
    employer_company_type: null,
  },
  {
    job_id: "CMfE_olpn88ocYgHAAAAAA==",
    job_posted_at_datetime_utc: "2023-12-27T14:04:59.000Z",
    job_offer_expiration_datetime_utc: "2024-01-26T14:04:59.000Z",
    job_publisher: "LinkedIn",
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=frontend+developer+in+hyderabad,india&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=frontend+developer+in+hyderabad,india&htidocid=CMfE_olpn88ocYgHAAAAAA%3D%3D",
    job_apply_link:
      "https://in.linkedin.com/jobs/view/frontend-developer-at-circuitry-ai-3788269448",
    job_is_remote: true,
    job_city: "Hyderabad",
    job_state: "TS",
    job_country: "IN",
    job_title: "Frontend Developer",
    job_employment_type: "FULLTIME",
    job_description:
      "Job Title: Front-End Developer (React)\n\nLocation: Hyderabad, India\n\nJob Type: Full-time\n\nPosition Overview: As a Front-End Developer at Circuitry.ai, you will play a crucial role in designing, developing, and maintaining user interfaces for our web and mobile applications. You will work closely with our design and back-end development teams to create visually stunning and highly functional interfaces that engage users and drive our products' success. The ideal candidate should be proficient in both React and React Native, have a strong understanding of front-end technologies, and be passionate about delivering exceptional user experiences across various platforms.\n\nKey Responsibilities:\n• Collaborate with cross-functional teams, including designers and back-end developers, to translate design mockups and user stories into responsive, interactive web and mobile applications.\n• Develop user-facing features using React.js and implement responsive web designs.\n• Build efficient and reusable components and front-end libraries\n• In-depth knowledge of JavaScript, CSS, HTML, Typescript, and front-end languages , Experience using ES2015 (ES6 / ES7)\n• Knowledge of REACT tools including React.js, Webpack, Enzyme, Redux, and Flux.\n• Experience with data structure libraries (e.g., Immutable.js)\n• Knowledge of modern authorization mechanisms, such as JWT mechanism and working with Okta.\n• Good understanding of asynchronous request handling, partial page updates for single-page applications.\n• Ability to work in an Agile /SCRUM environment.\n• Participate in code reviews and collaborate on architectural decisions.\n• Maintain and enhance existing codebases and peer-review code changes.\n\nQualifications:\n• Bachelor's degree in Computer Science, Web Development, or a related field (or equivalent experience).\n• 3 or more years of frontend experience with a product-based organization is recommended.\n• Proven experience as a Front-End Developer with a strong focus on React, React Native, and Node.JS\n• Proven experience in front-end development, specifically within Enterprise SaaS companies, demonstrating an understanding of the unique challenges and requirements of developing user interfaces for enterprise-level software.\n• Proficiency in JavaScript, HTML5, and CSS3.\n• Experience with state management libraries (e.g., Redux, MobX).\n• Knowledge of modern front-end build tools and package managers (e.g., Webpack, Babel, npm, yarn).\n• Familiarity with RESTful APIs and asynchronous request handling.\n• Responsive web design and mobile-first development experience.\n• Solid understanding of web and mobile performance optimization techniques.\n• Strong problem-solving skills and attention to detail.\n• Excellent communication and teamwork skills.\n• Ability to work independently and meet project deadlines.\n• Experience with version control systems (e.g., Github), deployment automation is a plus.",
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
    },
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 36,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_salary_currency: null,
    job_salary_period: null,
    job_min_salary: null,
    job_max_salary: null,
    job_latitude: 17.406498,
    job_longitude: 78.47724,
    job_highlights: {},
    job_apply_quality_score: 0.6875,
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
    job_benefits: null,
    employer_name: "Circuitry.ai",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqg7hLEftyxTJTlsebBjsfXNeYURotZDm9Ie08&s=0",
    employer_website: null,
    employer_company_type: null,
  },
];
// Use jobDetails wherever you need the structured job information.
